packages:
  - packages/*

catalog:
  # Can be referenced through "catalog:"
  "@vitejs/plugin-react": ^4.3.4
  react: ^18.2.0
  react-dom: ^18.2.0
  react-intl: ^7.1.1
  vite: ^6.0.7

catalogs:
  # Can be referenced through "catalog:old"
  old:
    react-intl: ^5.8.0